name: CICD on dev branch

on:
  push:
    branches: [dev]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test
        run: echo "run test"

  build:
    name: build-1.0.${{github.run_number}}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run build
        run: |
          echo "run build"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ozbillwang/hello-world:dev-1.0.${{github.run_number}},ozbillwang/hello-world:dev

  deploy:
    name: Deploy-DEV
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run deploy
        run: |
          echo "run deploy"
          docker run -i --rm ozbillwang/hello-world:dev-1.0.${{github.run_number}}
