on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

name: CICD

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test
        run: |
          echo "run test"

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run build
        run: |
          echo "run build"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run deploy
        run: |
          echo "run deploy"
