name: CICD at feature branches

on:
  push:
    branches-ignore:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test
        run: echo "run test"
