on:
  push:
    branches-ignore:
      - master
      - dev

name: CICD at feature branches

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
        echo "run test"
