on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CICD on master branch

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test
        run: echo "run test"

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run build
        run: |
          echo "run build"

  version:
    name: version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run version
        run: |
          echo "run version"
