on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CICD

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
