on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: CICD on versioning

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run deploy
        run: |
          echo "run deploy"
